apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: photoatom-postgres-client-cert
  namespace: photoatom-postgres-database
spec:
  secretName: photoatom-postgres-client-cert
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: photoatom-postgres-client-ca-issuer
    kind: Issuer
    group: cert-manager.io
