apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: photoatom-postgres-database
  labels:
    app: pg
spec:
  description: "PostgreSQL Cluster for all applications in PhotoAtom"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2

  enableSuperuserAccess: true

  instances: 3
  startDelay: 300
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: application
      postInitSQL:
        - CREATE USER keycloak
        - CREATE DATABASE keycloak OWNER keycloak
        - CREATE USER photoatom
        - CREATE DATABASE photoatom OWNER photoatom

  managed:
    roles:
      - connectionLimit: -1
        ensure: present
        inherit: true
        name: keycloak
        comment: Keycloak User for PostgreSQL
        login: true
        superuser: false
        createdb: true
        createrole: true
        replication: false
        bypassrls: false
        passwordSecret:
          name: photoatom-postgres-keycloak-creds

      - connectionLimit: -1
        ensure: present
        inherit: true
        name: photoatom
        comment: PhotoAtom User for PostgreSQL
        login: true
        superuser: false
        createdb: true
        createrole: true
        replication: false
        bypassrls: false
        passwordSecret:
          name: photoatom-postgres-photoatom-creds

  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  storage:
    size: 5Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path
      volumeMode: Filesystem

  backup:
    volumeSnapshot:
      className: csi-hostpath-snapclass
    barmanObjectStore:
      destinationPath: s3://postgres/
      endpointURL: https://minio-hl.photoatom-object-storage.svc.cluster.local:9000
      endpointCA:
        name: photoatom-postgres-minio-ca
        key: ca.crt
      s3Credentials:
        accessKeyId:
          name: photoatom-postgres-minio-access-key
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: photoatom-postgres-minio-access-key
          key: MINIO_ACCESS_SECRET
      wal:
        compression: gzip
      data:
        additionalCommandArgs:
          - "--min-chunk-size=5MB"
          - "--read-timeout=60"
          - "-vv"
